SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FINISH_LINE = SCREEN_HEIGHT/2

PLAYER_STARTING_POSITION = (0, -SCREEN_HEIGHT/2+20)
PLAYER_MOVE_DISTANCE = 10

CAR_MOVE_DISTANCE = 5
CAR_MOVE_INCREMENT = 10

SCORE_POSITION = (-SCREEN_WIDTH/2+80, SCREEN_HEIGHT/2-40)


RIGHT = 0
LEFT = 180
UP = 90
DOWN = 270

ALIGNMENT = 'center'
FONT = ('Courier', 30, 'normal')
