SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

LEFT_PADDLE_STARTING_POSITION = (-SCREEN_WIDTH/2+30, 0)
RIGHT_PADDLE_STARTING_POSITION = (SCREEN_WIDTH/2-40, 0)
PADDLE_MOVE_DISTANCE = 40

BALL_MOVE_DISTANCE = 10

RIGHT = 0
LEFT = 180
UP = 90
DOWN = 270

ALIGNMENT = 'center'
FONT = ('Courier', 80, 'normal')
